name: Laredo Git Action
run-name: Laredo Git Action
on: [push]

env:
    
  LAREDO_AWS_ACCESS_KEY_ID: $ {{ secrets.LAREDO_AWS_ACCESS_KEY_ID }}
  LAREDO_AWS_SECRET_KEY_ID: $ {{ secrets.LAREDO_AWS_SECRET_KEY_ID }}
  
jobs:

  Simple_Test_For_Now:
      runs-on: ubuntu-latest
      steps: 
      - name: checkout code from repo
        uses: actions/checkout@v4

      - name: Setup Terraform to Implement Cloud Infrastructure
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.3.0

      - name: Terraform Init
        run:  terraform init -backend-config="bucket=cicd-pipeline-store" -backend-config="key=env/CICD/terraform.tfstate"
      
      - name: Terraform Plan
        run:  terraform plan

      - name: Terraform apply
        run:  terraform apply --auto-approve
     